"""
Generates a complete Airflow DAG file from an IR WorkflowGraph.
Uses only standard Airflow + SQLAlchemy + pandas — no proprietary plugins.

Generation refuses to run if the IR graph still has missing references.
"""

from __future__ import annotations

import textwrap
from datetime import datetime

from ..models.ir import (
    ConnectionRef,
    Edge,
    Node,
    NodeKind,
    WorkflowGraph,
)
from .transformation_codegen import generate_transformation_callable
from ..parsers.ktr_parser import KNOWN_STEP_TYPES


# ---------------------------------------------------------------------------
# The DAG file template.  Sections marked {placeholder} are filled below.
# All literal { } in the emitted Python code are doubled: {{ }}.
# ---------------------------------------------------------------------------
DAG_TEMPLATE = '''\
# -*- coding: utf-8 -*-
"""
{description}

Auto-generated by pdi2airflow from: {source_kjb}
Generated at: {generated_at}
"""

from datetime import datetime, timedelta

import pandas as pd
import pendulum
from sqlalchemy import create_engine, text
from sqlalchemy.engine import URL as _SA_URL

from airflow import DAG
from airflow.hooks.base import BaseHook
from airflow.models import Variable
from airflow.operators.bash import BashOperator
from airflow.operators.dummy import DummyOperator
from airflow.operators.python import PythonOperator, BranchPythonOperator

# ----------------------------------------------------------------------
# Database helpers — standard SQLAlchemy + Airflow BaseHook.
# All generated task callables use these; do not rename them.
# ----------------------------------------------------------------------
def _pg_engine(conn_id):
    c = BaseHook.get_connection(conn_id)
    return create_engine(_SA_URL.create(
        "postgresql+psycopg2",
        username=c.login, password=c.password,
        host=c.host, port=c.port or 5432, database=c.schema,
    ))


def _mssql_engine(conn_id):
    c = BaseHook.get_connection(conn_id)
    return create_engine(_SA_URL.create(
        "mssql+pymssql",
        username=c.login, password=c.password,
        host=c.host, port=c.port or 1433, database=c.schema,
    ))


def _table_cols(engine, table):
    """Return column names for *table* (optionally schema-qualified)."""
    schema = table.split(".")[0] if "." in table else None
    tbl = table.split(".")[-1]
    from sqlalchemy import inspect as _sa_inspect
    return [col["name"] for col in _sa_inspect(engine).get_columns(tbl, schema=schema or None)]


def _exec_sql(engine, sql):
    """Execute *sql* on *engine* without returning rows."""
    with engine.begin() as conn:
        conn.execute(text(sql))


def _df_insert(df, engine, table, truncate=False):
    """Append *df* into *table*; optionally TRUNCATE first."""
    schema = table.split(".")[0] if "." in table else None
    tbl = table.split(".")[-1]
    if truncate:
        _exec_sql(engine, "TRUNCATE TABLE %s" % table)
    df.to_sql(tbl, engine, schema=schema, if_exists="append", index=False)


def _upsert_pg(df, engine, table, pkey):
    """PostgreSQL INSERT ... ON CONFLICT (pkey) DO UPDATE SET ..."""
    from psycopg2.extras import execute_values
    schema = table.split(".")[0] if "." in table else None
    tbl = table.split(".")[-1]
    cols = list(df.columns)
    qualified = ('"%s"."%s"' % (schema, tbl)) if schema else ('"%s"' % tbl)
    upd_cols = [c for c in cols if c not in pkey]
    conflict_cols = ", ".join('"%s"' % c for c in pkey)
    ins_cols = ", ".join('"%s"' % c for c in cols)
    if upd_cols:
        set_clause = ", ".join('"%s" = EXCLUDED."%s"' % (c, c) for c in upd_cols)
        on_conflict = "DO UPDATE SET %s" % set_clause
    else:
        on_conflict = "DO NOTHING"
    upsert_sql = (
        "INSERT INTO %s (%s) VALUES %%s ON CONFLICT (%s) %s"
        % (qualified, ins_cols, conflict_cols, on_conflict)
    )
    raw = engine.raw_connection()
    try:
        execute_values(raw.cursor(), upsert_sql, [tuple(r) for r in df.itertuples(index=False)])
        raw.commit()
    except Exception:
        raw.rollback()
        raise
    finally:
        raw.close()


# ----------------------------------------------------------------------
# Configuration
# ----------------------------------------------------------------------
local_tz = pendulum.timezone("Asia/Bangkok")

# run_date: converts UTC data_interval_end to local date.
# Adjust the timedelta offset if your cluster runs in a different timezone.
run_date = "{{{{ (data_interval_end + macros.timedelta(hours=7)).strftime('%Y-%m-%d') }}}}"

# ----------------------------------------------------------------------
# !! ACTION REQUIRED — verify all connection IDs before enabling this DAG !!
#
# Every CONN_* variable below was auto-mapped from a PDI connection.
# You MUST confirm each conn_id exists in Airflow (Admin -> Connections)
# and points to the correct host / database / credentials.
#
# Confidence levels:
#   exact      — PDI name matched an Airflow conn_id directly (safest)
#   host_match — matched by hostname + db type keyword (check carefully)
#   type_match — matched by db type only (HIGH RISK — verify manually)
# ----------------------------------------------------------------------
{connection_block}

# ----------------------------------------------------------------------
# Task callables (one per TRANSFORMATION / SQL / EVAL node)
# ----------------------------------------------------------------------
{callables_block}

# ----------------------------------------------------------------------
# DAG definition
# ----------------------------------------------------------------------
default_args = {{
    "owner": "airflow",
    "retries": 0,
}}

with DAG(
    dag_id="{dag_id}",
    default_args=default_args,
    description={description_repr},
    schedule_interval=None,  # TODO: set cron from PDI scheduler config
    start_date=datetime({start_year}, {start_month}, {start_day}, tzinfo=local_tz),
    tags={tags_repr},
    catchup=False,
    max_active_runs=1,
) as dag:

{operator_block}

{wiring_block}
'''


def generate_dag_source(graph: WorkflowGraph) -> str:
    """Render a complete .py DAG file from the IR graph."""
    ok, issues = graph.is_resolvable()
    if not ok:
        raise ValueError(
            "Cannot generate DAG: graph has unresolved references:\n  - "
            + "\n  - ".join(issues)
        )

    today = datetime.now()
    callables_src, callables_index = _build_callables(graph)

    return DAG_TEMPLATE.format(
        description=graph.description or graph.dag_id,
        source_kjb=graph.source_kjb or "<unknown>",
        generated_at=today.isoformat(timespec="seconds"),
        connection_block=_build_connection_block(graph.connections),
        callables_block=callables_src,
        dag_id=graph.dag_id,
        description_repr=repr(graph.description or graph.dag_id),
        start_year=today.year,
        start_month=today.month,
        start_day=today.day,
        tags_repr=repr(_build_tags(graph)),
        operator_block=textwrap.indent(_build_operator_block(graph, callables_index), "    "),
        wiring_block=textwrap.indent(_build_wiring_block(graph), "    "),
    )


def _build_tags(graph: WorkflowGraph) -> list[str]:
    tags = ["pdi-migrated"]
    desc = graph.description or ""
    if desc.startswith("[") and "]" in desc:
        repo_name = desc[1:desc.index("]")]
        if repo_name and repo_name not in tags:
            tags.append(repo_name)
    return tags


# ----------------------------------------------------------------------
# Sub-builders
# ----------------------------------------------------------------------

def _build_connection_block(conns: list[ConnectionRef]) -> str:
    if not conns:
        return "# (no PDI connections referenced)"
    _HINT = {
        "exact":      "",
        "host_match": "  # <- verify: matched by hostname keyword",
        "type_match": "  # <- HIGH RISK: matched by db type only — confirm this is the right connection",
        "none":       "  # <- UNRESOLVED: no mapping found — this should have blocked generation",
    }
    lines = []
    for c in conns:
        hint = _HINT.get(c.confidence, "")
        lines.append(
            f"# PDI '{c.pdi_name}' ({c.db_type}) -> Airflow '{c.suggested_airflow_conn}' "
            f"[confidence={c.confidence}]"
        )
        sanitized = ''.join(ch if ch.isalnum() or ch == '_' else '_' for ch in c.pdi_name.upper()).strip('_') or 'UNNAMED'
        var = f"CONN_{sanitized}"
        lines.append(f'{var} = "{c.suggested_airflow_conn}"{hint}')
    return "\n".join(lines)


def _safe_sql_literal(sql: str) -> str:
    """Render a SQL string as a safe Python literal (handles backslashes and triple quotes)."""
    if sql is None:
        return '""'
    cleaned = sql.replace('\\', '\\\\').replace('"""', '\\"\\"\\"')
    return f'"""{cleaned}"""'


def _build_callables(graph: WorkflowGraph) -> tuple[str, dict[str, str]]:
    """Returns (joined source code, {node_id: function_name})."""
    parts: list[str] = []
    index: dict[str, str] = {}
    for node in graph.nodes:
        if node.kind == NodeKind.TRANSFORMATION:
            fname, src = generate_transformation_callable(node, graph.connections)
            parts.append(src)
            index[node.id] = fname
        elif node.kind == NodeKind.SQL:
            fname = f"run_sql_{node.id}"
            conn_pdi = node.config.get("connection", "")
            airflow_conn = _airflow_id_for(conn_pdi, graph.connections) or f"TODO_{conn_pdi}"
            db_type = _db_type_for(conn_pdi, graph.connections)
            sql_lit = _safe_sql_literal(node.config.get("sql") or "")
            engine_fn = "_mssql_engine" if db_type == "MSSQL" else "_pg_engine"
            parts.append(textwrap.dedent(f"""
                def {fname}(**context):
                    \"\"\"Translated from PDI SQL job entry: {node.label}\"\"\"
                    _engine = {engine_fn}("{airflow_conn}")
                    _exec_sql(_engine, {sql_lit})
            """).strip())
            index[node.id] = fname
        elif node.kind == NodeKind.EVAL:
            fname = f"branch_{node.id}"
            script = (node.config.get("script") or "").strip()
            parts.append(textwrap.dedent(f"""
                def {fname}(**context):
                    \"\"\"Translated from PDI EVAL job entry: {node.label}
                    Original PDI script:
                    {script!r}
                    TODO: implement branching logic. Return downstream task_id(s).
                    \"\"\"
                    return []  # TODO: list of task_ids to run
            """).strip())
            index[node.id] = fname
    return ("\n\n\n".join(parts) if parts else "# (no callables needed)"), index


def _build_operator_block(graph: WorkflowGraph, callables_index: dict[str, str]) -> str:
    """Emit one operator instantiation per IR node."""
    lines: list[str] = []
    for node in graph.nodes:
        if node.kind == NodeKind.START:
            lines.append(f'{node.id} = DummyOperator(task_id="{node.id}")')
        elif node.kind == NodeKind.END:
            lines.append(textwrap.dedent(f'''\
                {node.id} = DummyOperator(
                    task_id="{node.id}",
                    trigger_rule="none_failed",
                )''').strip())
        elif node.kind == NodeKind.DUMMY:
            lines.append(f'{node.id} = DummyOperator(task_id="{node.id}")')
        elif node.kind == NodeKind.TRANSFORMATION:
            fname = callables_index.get(node.id, "lambda **k: None")
            lines.append(textwrap.dedent(f'''\
                {node.id} = PythonOperator(
                    task_id="{node.id}",
                    python_callable={fname},
                )''').strip())
        elif node.kind == NodeKind.SQL:
            fname = callables_index.get(node.id, "lambda **k: None")
            lines.append(textwrap.dedent(f'''\
                {node.id} = PythonOperator(
                    task_id="{node.id}",
                    python_callable={fname},
                )''').strip())
        elif node.kind == NodeKind.SHELL:
            script = (node.config.get("script") or "").replace('"', '\\"')
            lines.append(textwrap.dedent(f'''\
                {node.id} = BashOperator(
                    task_id="{node.id}",
                    bash_command="""{script}""",
                )''').strip())
        elif node.kind == NodeKind.EVAL:
            fname = callables_index.get(node.id, "lambda **k: []")
            lines.append(textwrap.dedent(f'''\
                {node.id} = BranchPythonOperator(
                    task_id="{node.id}",
                    python_callable={fname},
                )''').strip())
        elif node.kind == NodeKind.WAITFOR:
            timeout = node.config.get("maximum_timeout", "0")
            lines.append(textwrap.dedent(f'''\
                # PDI WAITFOR: {node.label} (timeout={timeout}s)
                # TODO: replace with TimeDeltaSensor or appropriate sensor
                {node.id} = DummyOperator(task_id="{node.id}")''').strip())
        elif node.kind == NodeKind.SUBJOB:
            lines.append(textwrap.dedent(f'''\
                # PDI SUBJOB: {node.label}
                # TODO: replace with TriggerDagRunOperator targeting the migrated sub-DAG
                {node.id} = DummyOperator(task_id="{node.id}")''').strip())
        else:
            lines.append(textwrap.dedent(f'''\
                # UNKNOWN PDI entry type — review original .kjb
                {node.id} = DummyOperator(task_id="{node.id}")''').strip())
    return "\n".join(lines)


def _build_wiring_block(graph: WorkflowGraph) -> str:
    """Emit `a >> b` lines from edges. Group by source for readability."""
    if not graph.edges:
        return "# (no edges)"
    by_src: dict[str, list[str]] = {}
    for e in graph.edges:
        by_src.setdefault(e.source, []).append(e.target)
    lines: list[str] = []
    for src, tgts in by_src.items():
        if len(tgts) == 1:
            lines.append(f"{src} >> {tgts[0]}")
        else:
            tgt_list = ", ".join(tgts)
            lines.append(f"{src} >> [{tgt_list}]")
    return "\n".join(lines)


def _airflow_id_for(pdi_name: str, conns: list[ConnectionRef]) -> str | None:
    for c in conns:
        if c.pdi_name == pdi_name:
            return c.suggested_airflow_conn
    return None


def _db_type_for(pdi_name: str, conns: list[ConnectionRef]) -> str:
    for c in conns:
        if c.pdi_name == pdi_name:
            return (c.db_type or "").upper()
    return "UNKNOWN"


# ----------------------------------------------------------------------
# Migration report
# ----------------------------------------------------------------------

_CONF_BADGE = {
    "exact":      "✅ exact",
    "host_match": "⚠️ host\\_match",
    "type_match": "🔴 type\\_match",
    "none":       "❌ none",
}
_CONF_ACTION = {
    "exact":      "Confirm conn\\_id exists in Airflow.",
    "host_match": "**Verify** host, database, and credentials match.",
    "type_match": "**HIGH RISK** — matched by DB type only. Manually confirm the correct conn\\_id.",
    "none":       "**UNRESOLVED** — no mapping found.",
}


def generate_migration_report(graph: WorkflowGraph) -> str:
    """A markdown summary documenting how the DAG maps back to the PDI source."""
    lines = [
        f"# Migration Report — `{graph.dag_id}`",
        "",
        f"Source: `{graph.source_kjb or 'unknown'}`",
        f"Description: {graph.description or '_(none)_'}",
        "",
        "> [!WARNING]",
        "> **ACTION REQUIRED — verify all connections before enabling this DAG.**",
        "> ",
        "> Each `CONN_*` variable in the generated `.py` file was auto-mapped from a PDI",
        "> connection definition. You **must** confirm every conn\\_id exists in Airflow",
        "> (**Admin → Connections**) and points to the correct host, database, and credentials.",
        "> ",
        "> | Badge | Confidence | What to do |",
        "> |---|---|---|",
        "> | ✅ exact | PDI name matched an Airflow conn\\_id directly | Still confirm it exists |",
        "> | ⚠️ host\\_match | Matched by hostname / DB-type keyword | Verify host, DB, credentials |",
        "> | 🔴 type\\_match | Matched by DB type only | **Manually identify the right conn\\_id** |",
        "",
        "## Connections",
        "",
    ]
    if graph.connections:
        lines.append("| PDI Name | Type | Host | Database | Airflow conn\\_id | Confidence | Action |")
        lines.append("|---|---|---|---|---|---|---|")
        for c in graph.connections:
            badge  = _CONF_BADGE.get(c.confidence, c.confidence)
            action = _CONF_ACTION.get(c.confidence, "")
            lines.append(
                f"| `{c.pdi_name}` | {c.db_type} | {c.host or '-'} | "
                f"{c.database or '-'} | `{c.suggested_airflow_conn or '?'}` | {badge} | {action} |"
            )
    else:
        lines.append("_No connections referenced._")

    lines.extend(["", "## Variables", ""])
    if graph.variables:
        lines.append("| Variable | Used by tasks | Default |")
        lines.append("|---|---|---|")
        for v in graph.variables:
            lines.append(
                f"| `${{{v.name}}}` | {', '.join(v.used_in) or '-'} | "
                f"{v.default_value or '_(none — set as Airflow Variable)_'} |"
            )
    else:
        lines.append("_No variables referenced._")

    lines.extend(["", "## Tasks", ""])
    lines.append("| Task ID | Kind | Source | Notes |")
    lines.append("|---|---|---|---|")
    for n in graph.nodes:
        notes = ""
        if n.kind == NodeKind.TRANSFORMATION and n.steps:
            unmapped = sorted({s.pdi_type for s in n.steps if s.pdi_type not in KNOWN_STEP_TYPES})
            if unmapped:
                notes = "Unmapped step types: " + ", ".join(unmapped)
        lines.append(f"| `{n.id}` | {n.kind.value} | {n.source_file or '-'} | {notes} |")

    if graph.unmapped_step_types:
        lines.extend([
            "",
            "## Unmapped PDI Step Types",
            "",
            "These PDI step types have no translation; the generated code",
            "contains TODO stubs that must be implemented manually:",
            "",
        ])
        for t in graph.unmapped_step_types:
            lines.append(f"- `{t}`")

    return "\n".join(lines) + "\n"
